# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0c33575c64279b882fcaf4fb05462554bfc9360c9367092d4cda9dc8685d40f556820a501d06675f522b6d5a46ebe94ba71d0337ee98c13a5781154ffd563f2

test:
  secret_key_base: dbcdb7e4b13000f79e9c807fa1051e10b6b91f63d82873631d3cc55cd5cf8d1efd67c7b78d1cc5cbae78426d3281832eb96d9e9c23127ed81a46ec63314b2fce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
